# Documentation: https://github.com/JuliaCI/Appveyor.jl
environment:
  my_variable:
    secure: 3wOFkOfbSJiJ1XDrrjdfGcP6AIQs8eyitPJfhAGf7q0uo0260hQmjx98W9fINp8D
  matrix:
    - julia_version: 1.11
    # - julia_version: 1.6
    - julia_version: nightly
platform:
  - x64
cache:
  - '%USERPROFILE%\.julia\artifacts'
matrix:
  allow_failures:
    - julia_version: nightly
branches:
  only:
    - main
    - /release-.*/
notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
install:
  - ps: iex ((new-object net.webclient).DownloadString("https://raw.githubusercontent.com/JuliaCI/Appveyor.jl/version-1/bin/install.ps1"))
build_script:
  - C:\julia\bin\julia -e "using Pkg; Pkg.activate(pwd()); Pkg.instantiate(); Pkg.test(coverage=true)"
  - echo "%JL_BUILD_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_BUILD_SCRIPT%"
test_script:
  - echo "%JL_TEST_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_TEST_SCRIPT%"
after_test:
  - C:\julia\bin\julia -e "using Pkg; Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(process_folder())"
on_success:
  - echo "%JL_CODECOV_SCRIPT%"
  - C:\julia\bin\julia -e "%JL_CODECOV_SCRIPT%"
