name = "SynergisticGaussianSystems"
uuid = "9f166eec-3261-4817-8b44-7cd93ebc043f"
authors = ["Enrico Caprioglio"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
